insert into skill (skillid, description) values (null, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into skill (skillid, description) values (null, 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into skill (skillid, description) values (null, 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into skill (skillid, description) values (null, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into skill (skillid, description) values (null, 'Nullam molestie nibh in lectus.');
insert into skill (skillid, description) values (null, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into skill (skillid, description) values (null, 'In hac habitasse platea dictumst.');
insert into skill (skillid, description) values (null, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into skill (skillid, description) values (null, 'Suspendisse ornare consequat lectus.');
insert into skill (skillid, description) values (null, 'Duis aliquam convallis nunc.');
